// JavaScript Document

//generated by Eden Juscelino

/**********
*********/




	$(document).ready(function() {
    var x_timer;    
        
    $("#user_id").keyup(function (e){
        
             
        clearTimeout(x_timer);
        var user_name = $(this).val();
        x_timer = setTimeout(function(){
            check_username_ajax(user_name);
        }, 1000);
    }); 

        
function check_username_ajax(user_id){ //checking the username
    $("#user-result").html('<img src="images/loader.gif" height="42" width="42" >');
    $.post('user_name.php', {'user_id':user_id}, function(data) {
      $("#user-result").html(data);
        
        
        var available_Id = "<p class='right'> The ID is available</p>";
       
        var get_id_result = String(data).trim(); //trim the value  of data
        
        
        
       if(get_id_result == available_Id ){
           
        document.getElementById('signup_button').disabled = false;
        }else{
             document.getElementById('signup_button').disabled = true;
        }
       
        
        var eden = $("#user-result").html(data);
      
    });
}
        
              
}); 

    $(document).ready(function() { //checking if the email is correct
        var x_timer;   
        var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
        
        $("#email").keyup(function (e){
              
        clearTimeout(x_timer);
        var email = $(this).val();
        x_timer = setTimeout(function(){
           
            check_email_ajax(email);
        }, 1000);
    });
      
      function check_email_ajax(email){
          
      if (!(email).match(emailReg)) {
          
          
          $("#email-result").html("<p class='wrong'>invalid e-mail</p>");
           document.getElementById('signup_button').disabled = true;
   
} else{
          
    $("#email-result").html('<img src="imgs/loader.gif" height="42" width="42" >');
    
    $.post('user_name.php', {'email':email}, function(data) {
        
       var right_email ="<p class='right'> the e-mail is available</p>";
        
        var wrong_email = "<p  class='wrong'> this e-mail not available</p>";
        
       
        var get_email_result = String(data).trim();
        
        console.log(String(data).trim());
        console.log(get_email_result);
        
        if(get_email_result === right_email){
           
           
        document.getElementById('signup_button').disabled = false;
        }else if (String(get_email_result) === String(wrong_email)){
            
            document.getElementById('signup_button').disabled = true;
        }
        
        
      
        
        $("#email-result").html(data);
       
      
        
    });
} // end of if-else
          
} // end of check e-mail
        

 

           
});




function checkPasswordMatch() { //password checking function
   
    var pass1 = document.getElementById('password1');
    var pass2 = document.getElementById('password2');
     if(pass1.value == pass2.value){
         
         $("#password-result").html("<p class='right'> passwords match</p>");
         document.getElementById('signup_button').disabled = false;
         
     }else{
         
        
         
         $("#password-result").html("<p  class='wrong'>passwords don't much match</p>");
         document.getElementById('signup_button').disabled = true;
         
         
     }

}

      